version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run: python --version

# VS Code Extension Version: 1.5.1